title: 02 Scouts Host
author:
  name: 02 Raffles Scout Group
  email: 02raffles.gsl@gmail.com
  
description:
  (c) matt group webdev 2023-2025
  
remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme
  
logo: /favicon.png

header_pages:
  - index.md

minima:
  skin: solarized-light

  minima:
  social_links:
    - { platform: instagram, user_url: "https://instagram.com/02rafflesscouts" }
    - { platform: youtube, user_url: "https://youtube.com/@matt_wyz" }
