title: 02 Scouts Filehost
author:
  name: 02 Raffles Scouts
  email: hello@02scouts.org
  
description:
  a matt group webdev site - (c) 2023-2025
  No part of this site shall be reproduced in any way, shape or form.
  
logo: /favicon.png

header_pages:
  - index.md
  - IPCS.md
  - sotwarchive.md
  - 02sotw.md
