title: matt_wyz
author:
  name: Matthew W.
  email: matthew@mattwyz.xyz
  
description:
  (c) matthew w. 2023-2025
  Powered by Github Pages
  
logo: /favicon.png

header_pages:
  - index.md
  - sotwarchive.md
  - 02sotw.md
