title: 02 Scouts Filehost
author:
  name: 02 Raffles Scouts
  email: 02scouts.gsl@gmail.com
  
description:
  (c) 02 Raffles Scouts 2023-2025
  
logo: /favicon.png

header_pages:
  - index.md
  - sotwarchive.md
  - 02sotw.md
